# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: qconnect_envelope.proto
# Protobuf Python Version: 6.33.3
"""Generated protocol buffer code."""

from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder

_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC, 6, 33, 3, "", "qconnect_envelope.proto"
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(
    b'\n\x17qconnect_envelope.proto\x12\x08qconnect";\n\x0c\x41uthenticate\x12\r\n\x05msgId\x18\x01 \x01(\r\x12\x0f\n\x07msgDate\x18\x02 \x01(\x04\x12\x0b\n\x03jwt\x18\x03 \x01(\t"L\n\tSubscribe\x12\r\n\x05msgId\x18\x01 \x01(\r\x12\x0f\n\x07msgDate\x18\x02 \x01(\x04\x12\r\n\x05proto\x18\x03 \x01(\r\x12\x10\n\x08\x63hannels\x18\x04 \x03(\x0c"N\n\x0bUnsubscribe\x12\r\n\x05msgId\x18\x01 \x01(\r\x12\x0f\n\x07msgDate\x18\x02 \x01(\x04\x12\r\n\x05proto\x18\x03 \x01(\r\x12\x10\n\x08\x63hannels\x18\x04 \x03(\x0c"e\n\x07Payload\x12\r\n\x05msgId\x18\x01 \x01(\r\x12\x0f\n\x07msgDate\x18\x02 \x01(\x04\x12\r\n\x05proto\x18\x03 \x01(\r\x12\x0b\n\x03src\x18\x04 \x01(\x0c\x12\r\n\x05\x64\x65sts\x18\x05 \x03(\x0c\x12\x0f\n\x07payload\x18\x07 \x01(\x0c"?\n\nDisconnect\x12\r\n\x05msgId\x18\x01 \x01(\r\x12\x0f\n\x07msgDate\x18\x02 \x01(\x04\x12\x11\n\treconnect\x18\x03 \x01(\x08*\x92\x01\n\x11QCloudMessageType\x12#\n\x1fQCLOUD_MESSAGE_TYPE_UNSPECIFIED\x10\x00\x12\x10\n\x0c\x41UTHENTICATE\x10\x01\x12\r\n\tSUBSCRIBE\x10\x02\x12\x0f\n\x0bUNSUBSCRIBE\x10\x03\x12\x0b\n\x07PAYLOAD\x10\x06\x12\t\n\x05\x45RROR\x10\t\x12\x0e\n\nDISCONNECT\x10\n*R\n\x0bQCloudProto\x12\x0e\n\nQP_UNKNOWN\x10\x00\x12\x0f\n\x0bQP_QCONNECT\x10\x01\x12\x10\n\x0cQP_QCONNECT2\x10\x02\x12\x10\n\x0cQP_QCONNECT3\x10\x03'
)

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, "qconnect_envelope_pb2", _globals)
if not _descriptor._USE_C_DESCRIPTORS:
    DESCRIPTOR._loaded_options = None
    _globals["_QCLOUDMESSAGETYPE"]._serialized_start = 425
    _globals["_QCLOUDMESSAGETYPE"]._serialized_end = 571
    _globals["_QCLOUDPROTO"]._serialized_start = 573
    _globals["_QCLOUDPROTO"]._serialized_end = 655
    _globals["_AUTHENTICATE"]._serialized_start = 37
    _globals["_AUTHENTICATE"]._serialized_end = 96
    _globals["_SUBSCRIBE"]._serialized_start = 98
    _globals["_SUBSCRIBE"]._serialized_end = 174
    _globals["_UNSUBSCRIBE"]._serialized_start = 176
    _globals["_UNSUBSCRIBE"]._serialized_end = 254
    _globals["_PAYLOAD"]._serialized_start = 256
    _globals["_PAYLOAD"]._serialized_end = 357
    _globals["_DISCONNECT"]._serialized_start = 359
    _globals["_DISCONNECT"]._serialized_end = 422
# @@protoc_insertion_point(module_scope)
