# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: ws.proto
# Protobuf Python Version: 6.33.3
"""Generated protocol buffer code."""

from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder

_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC, 6, 33, 3, "", "ws.proto"
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(
    b'\n\x08ws.proto"B\n\tWSWelcome\x12\x15\n\rws_request_id\x18\x01 \x01(\x04\x12\x11\n\ttimestamp\x18\x02 \x01(\x04\x12\x0b\n\x03jwt\x18\x03 \x01(\x0c"p\n\x06WSInfo\x12\x15\n\rws_request_id\x18\x01 \x01(\x04\x12\x11\n\ttimestamp\x18\x02 \x01(\x04\x12\x10\n\x08unknown1\x18\x03 \x01(\x08\x12\x10\n\x08unknown2\x18\x05 \x01(\x0c\x12\x18\n\x07ws_data\x18\x07 \x01(\x0b\x32\x07.WSData"\xdc\x02\n\x06WSData\x12\x11\n\tdevice_id\x18\x01 \x01(\x06\x12\x12\n\nmessage_id\x18\x02 \x01(\x04\x12\x1a\n\x04info\x18\x03 \x01(\x0b\x32\x0c.WSData.Info\x1a\x8e\x02\n\x04Info\x12\x0c\n\x04kind\x18\x01 \x01(\r\x12$\n\nplay_block\x18\x1d \x01(\x0b\x32\x0e.empty_messageH\x00\x12$\n\x0c\x64\x65vice_block\x18= \x01(\x0b\x32\x0c.ClientBlockH\x00\x12#\n\x0bplaying_for\x18? \x01(\x0b\x32\x0c.StatusBlockH\x00\x12"\n\nactive_for\x18M \x01(\x0b\x32\x0c.StatusBlockH\x00"[\n\x04Kind\x12\x10\n\x0cKIND_UNKNOWN\x10\x00\x12\r\n\tKIND_PLAY\x10\x1d\x12\x0f\n\x0bKIND_DEVICE\x10=\x12\x10\n\x0cKIND_PLAYING\x10?\x12\x0f\n\x0bKIND_STATUS\x10MB\x06\n\x04\x64\x61ta"\x0f\n\rempty_message"#\n\x0bStatusBlock\x12\x14\n\x0ctimestamp_ms\x18\x01 \x01(\x04"+\n\x0b\x43lientBlock\x12\x1c\n\x07\x64\x65tails\x18\x02 \x01(\x0b\x32\x0b.DeviceInfo"q\n\nDeviceInfo\x12\x11\n\topaque_id\x18\x01 \x01(\x0c\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x10\n\x08platform\x18\x06 \x01(\r\x12\x1b\n\x04\x63\x61ps\x18\x07 \x01(\x0b\x32\r.Capabilities\x12\x13\n\x0b\x61pp_version\x18\x08 \x01(\t"/\n\x0c\x43\x61pabilities\x12\t\n\x01\x61\x18\x01 \x01(\r\x12\t\n\x01\x62\x18\x02 \x01(\r\x12\t\n\x01\x63\x18\x03 \x01(\r'
)

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, "ws_pb2", _globals)
if not _descriptor._USE_C_DESCRIPTORS:
    DESCRIPTOR._loaded_options = None
    _globals["_WSWELCOME"]._serialized_start = 12
    _globals["_WSWELCOME"]._serialized_end = 78
    _globals["_WSINFO"]._serialized_start = 80
    _globals["_WSINFO"]._serialized_end = 192
    _globals["_WSDATA"]._serialized_start = 195
    _globals["_WSDATA"]._serialized_end = 543
    _globals["_WSDATA_INFO"]._serialized_start = 273
    _globals["_WSDATA_INFO"]._serialized_end = 543
    _globals["_WSDATA_INFO_KIND"]._serialized_start = 444
    _globals["_WSDATA_INFO_KIND"]._serialized_end = 535
    _globals["_EMPTY_MESSAGE"]._serialized_start = 545
    _globals["_EMPTY_MESSAGE"]._serialized_end = 560
    _globals["_STATUSBLOCK"]._serialized_start = 562
    _globals["_STATUSBLOCK"]._serialized_end = 597
    _globals["_CLIENTBLOCK"]._serialized_start = 599
    _globals["_CLIENTBLOCK"]._serialized_end = 642
    _globals["_DEVICEINFO"]._serialized_start = 644
    _globals["_DEVICEINFO"]._serialized_end = 757
    _globals["_CAPABILITIES"]._serialized_start = 759
    _globals["_CAPABILITIES"]._serialized_end = 806
# @@protoc_insertion_point(module_scope)
